contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #pairgenomealignmask channel"
    url: https://nfcore.slack.com/channels/pairgenomealignmask
    about: Discussion about the nf-core/pairgenomealignmask pipeline
